### ISSUE TITLE
Playerlist does not show when only 1 person on the server

### ISSUE THREAD

**Issue by fixel99** [kubastick/MC-Server-Status-Discord-Bot#1]
![result](https://user-images.githubusercontent.com/11691966/51793687-7f312f00-2218-11e9-890c-9228b485b2d9.png)

Works fine with any other amount of players i've tested.

**Comment by fixel99** [comment]
Opened a pull request #2 to fix this

**Comment by kubastick** [comment]
Merged, thank you for your contribution
